### ISSUE TITLE
make bibtext keys readable 

### ISSUE THREAD

**Issue by lexingxie** [HMIANU2023/bibtex#2]
As a general convention, it'll be good to make bibtex keys somewhat sensible. 
e.g. instead of "RN48", something like "bateman2019algorithmic" (first author, year, first word in title .. but feel free to make up your own rule) 

this won't affect our website, but is a good habit for bibtex (when it's used for referencing in papers)

**Comment by HMIANU2023** [comment]
19dbb4207a362dd105028fe8d4f84ae58f4d5630
