### ISSUE TITLE
Please add a new entry for Alex Soen's recent NeuRIPS paper

### ISSUE THREAD

**Issue by lexingxie** [HMIANU2023/bibtex#5]
@inproceedings{Soen2022FairWF,
  title={Fair Wrapping for Black-box Predictions},
  author={Alexander Soen and Ibrahim M. Alabdulmohsin and Sanmi Koyejo and Y. Mansour and Nyalleng Moorosi and Richard Nock and Ke Sun and Lexing Xie},
  booktitle = {36th Conference on Neural Information Processing Systems (NeurIPS 2022)},
  year      = {2022},
  url_paper = {https://arxiv.org/pdf/2201.12947.pdf},
  abstract  = {We introduce a new family of techniques to post-process ("wrap") a black-box classifier in order to reduce its bias. Our technique builds on the recent analysis of improper loss functions whose optimization can correct any twist in prediction, unfairness being treated as a twist. In the post-processing, we learn a wrapper function which we define as an α-tree, which modifies the prediction. We provide two generic boosting algorithms to learn α-trees. We show that our modification has appealing properties in terms of composition of α-trees, generalization, interpretability, and KL divergence between modified and original predictions. We exemplify the use of our technique in three fairness notions: conditional value-at-risk, equality of opportunity, and statistical parity; and provide experiments on several readily available datasets.}
}

**Comment by HMIANU2023** [comment]
5dd5e90e93177b4737ee83703e366114d6840a42
<img width="282" alt="image" src="https://user-images.githubusercontent.com/119158101/205950000-73493652-031d-4d78-be3d-fd3d43da5771.png">
