### ISSUE TITLE
please fix the year field of the following papers

### ISSUE THREAD

**Issue by lexingxie** [HMIANU2023/bibtex#6]
Transform and Tell: Entity-Aware News Image Captioning, A Tran, A Mathews, and L Xie, Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR),

--> this should be 2020 

Variation across Scales: Measurement Fidelity under Twitter Data Sampling, Siqi Wu, M Rizoiu, and L Xie, Proceedings of the Fourteenth International AAAI Conference on Web and Social Media 2020,

--> this already says 2020 but not sure why it's not showing? 

thanks!

**Comment by HMIANU2023** [comment]
6e54a867d7d440d9bd0b65ce545605f0d710ecf0, 1ca0a0c3f059e8c2e82354fa7be5b75d6038803e

**Comment by lexingxie** [comment]
please re-open this issue until solved? 
the entry on the website is still showing no year 
![image](https://user-images.githubusercontent.com/2434228/205767306-e655a065-7741-46eb-ba90-239259218706.png)


Thanks!

**Comment by HMIANU2023** [comment]
6e54a867d7d440d9bd0b65ce545605f0d710ecf0,

**Comment by HMIANU2023** [comment]
the issue is already fixed. The entry code needs to update on the HMI website < hmi.anu.edu.au>, it won't work if updated on the copy website.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/119158101/205947516-97616902-7a57-4d3c-af5a-f8323307006e.png">
